name = "form"
type = "javascript"
main = ".svelte-kit/cloudflare/worker.js"
site = { bucket = ".svelte-kit/cloudflare/client" }
compatibility_date = "2024-01-01"

[env.production]
vars = { ENVIRONMENT = "production" }
