name = "form"
main = ".svelte-kit/cloudflare/index.js"
compatibility_date = "2024-01-01"

[assets]
directory = ".svelte-kit/cloudflare/client"
binding = "ASSETS"

[env.production]
vars = { ENVIRONMENT = "production" }
